kernel/3.10: backport of_pci_get_devfn function from 3.11
Fixes the following build error on ramips/rt3883:

  arch/mips/pci/pci-rt3883.c:488:3: error: implicit declaration of function \
  'of_pci_get_devfn' [-Werror=implicit-function-declaration]
  cc1: some warnings being treated as errors

Although the function is only used by the PCI driver
of the RT3883 SoC but at the moment but it might be
useful for other targets as well.

Signed-off-by: Michael Lee <igvtee@gmail.com>
Signed-off-by: Gabor Juhos <juhosg@openwrt.org>

git-svn-id: svn://svn.openwrt.org/openwrt@37826 3c298f89-4303-0410-b956-a3cf2f4a3e73